version: "3.7"

services:
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./docker/server:/var/lib/server
      - ./migrations:/migrations
    environment:
      APP_ENV: ${APP_ENV}
      TZ: Asia/Tokyo
      PORT: 8080
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_ADDR: db:3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ocw-central
      MIGRATIONS_DIR: /migrations
      WAIT_HOSTS: db:3306
  db:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ocw-central
