version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    environment:
      TZ: Asia/Tokyo
      PORT: ${PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ADDR: ${MYSQL_ADDR}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DEFAULT_REGION_NAME: ${DEFAULT_REGION_NAME}
      APP_ENV: ${APP_ENV}
  db:
    image: mysql:8.0.30
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
