package main

import (
	"log"
	"net/http"
	"regexp"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/kafugen/ocwcentral/env"
	"github.com/kafugen/ocwcentral/graph/generated"
)

func main() {
	env := env.NewEnvConfig()

	var frontendOrigin string
	var re *regexp.Regexp  // only used when env.AppEnv == "DEV"
	if env.AppEnv == "LOCAL" {
		frontendOrigin = "http://127.0.0.1:5173"
	} else if env.AppEnv == "DEV"{
		// The origin of the frontend app in dev environment
		// is randomly generated by the Cloudflare pages as a preview URL.
		// Thus, we need to determine the origin dynamically
		// in the callback function of http.HandlerFunc.
		re = regexp.MustCompile(`^https://[a-z0-9]+\.ocwcentral\.pages\.dev$`)
	} else if env.AppEnv == "PROD" {
		frontendOrigin = "https://ocwcentral.com"
	} else {
		panic("invalid APP_ENV")
	}

	resolver := InitializeResolver()

	srv := handler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{Resolvers: &resolver}))
	http.HandleFunc("/query", func(w http.ResponseWriter, r *http.Request) {
		if env.AppEnv == "DEV" && re.MatchString(r.Header.Get("Origin")) {
			frontendOrigin = r.Header.Get("Origin")
		}

		w.Header().Set("Access-Control-Allow-Headers", "*")
		w.Header().Set("Access-Control-Allow-Origin", frontendOrigin)
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		srv.ServeHTTP(w, r)
	})
	// Handle playground for DEV environment
	if env.AppEnv == "DEV" {
		http.Handle("/playground", playground.Handler("GraphQL playground", "/query"))
		log.Printf("connect to http://localhost:%s/playground for GraphQL playground", env.Port)
	}
	log.Fatal(http.ListenAndServe(":"+env.Port, nil))
}
