// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kafugen/ocwcentral/env"
	"github.com/kafugen/ocwcentral/graph"
	"github.com/kafugen/ocwcentral/interactor"
	"github.com/kafugen/ocwcentral/persistence"
)

// Injectors from wire.go:

func InitializeResolver() graph.Resolver {
	envConfig := env.NewEnvConfig()
	db := persistence.NewDB(envConfig)
	subjectRepositoryImpl := persistence.NewSubjectRepositoryImpl(db)
	subjectInteractor := interactor.NewSubjectInteractor(subjectRepositoryImpl)
	videoRepositoryImpl := persistence.NewVideoRepositoryImpl(db)
	videoInteractor := interactor.NewVideoInteractor(videoRepositoryImpl)
	resourceRepositoryImpl := persistence.NewResourceRepositoryImpl(db)
	resourceInteractor := interactor.NewResourceInteractor(resourceRepositoryImpl)
	syllabusRepositoryImpl := persistence.NewSyllabusRepositoryImpl(db)
	syllabusInteractor := interactor.NewSyllabusInteractor(syllabusRepositoryImpl)
	academicFieldRepositoryImpl := persistence.NewAcademicFieldRepositoryImpl(db)
	academicFieldInteractor := interactor.NewAcademicFieldInteractor(academicFieldRepositoryImpl)
	resolver := graph.NewResolver(subjectInteractor, videoInteractor, resourceInteractor, syllabusInteractor, academicFieldInteractor)
	return resolver
}
