// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kafugen/ocwcentral/graph"
	"github.com/kafugen/ocwcentral/interactor"
	"github.com/kafugen/ocwcentral/persistence"
)

// Injectors from wire.go:

func InitializeResolver() graph.Resolver {
	subjectRepositoryImpl := persistence.NewSubjectRepositoryImpl()
	subjectInteractor := interactor.NewSubjectInteractor(subjectRepositoryImpl)
	videoRepositoryImpl := persistence.NewVideoRepositoryImpl()
	videoInteractor := interactor.NewVideoInteractor(videoRepositoryImpl)
	resourceRepositoryImpl := persistence.NewResourceRepositoryImpl()
	resourceInteractor := interactor.NewResourceInteractor(resourceRepositoryImpl)
	syllabusRepositoryImpl := persistence.NewSyllabusRepositoryImpl()
	syllabusInteractor := interactor.NewSyllabusInteractor(syllabusRepositoryImpl)
	resolver := graph.NewResolver(subjectInteractor, videoInteractor, resourceInteractor, syllabusInteractor)
	return resolver
}
