BEGIN;

DROP TABLE IF EXISTS subject_related_subjects;

DROP TABLE IF EXISTS subpages;

DROP TABLE IF EXISTS resources;

DROP TABLE IF EXISTS chapters;

DROP TABLE IF EXISTS syllabuses;

DROP TABLE IF EXISTS videos;

DROP TABLE IF EXISTS subjects;

COMMIT;
